---

- name: Systemd socket
  block:
    - name: "Create systemd socket unit {{ _common_service_name }}"
      ansible.builtin.template:
        src: "{{ _common_service_name }}.socket.j2"
        dest: "/etc/systemd/system/{{ _common_service_name }}.socket"
        owner: root
        group: root
        mode: '0644'
      become: true
      notify:
        - "Restart {{ _common_service_name }}"
      tags:
        - jellyfin_exporter
        - configure
        - jellyfin_exporter_configure
  rescue:
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system
        state: pre
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: "/etc/systemd/system/{{ _common_service_name }}.socket"
        state: pre
    - name: "Create systemd service unit (immutable) {{ _common_service_name }}"
      ansible.builtin.template:
        src: "{{ _common_service_name }}.socket.j2"
        dest: "/etc/systemd/system/{{ _common_service_name }}.socket"
        owner: root
        group: root
        mode: '0644'
      become: true
      notify:
        - "Restart {{ _common_service_name }}"
      tags:
        - jellyfin_exporter
        - configure
        - jellyfin_exporter_configure
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system
        state: post
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: "/etc/systemd/system/{{ _common_service_name }}.socket"
        state: post
