---
collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
  - name: https://github.com/ansible-collections/community.crypto.git
    type: git

roles:
  - src: https://github.com/juju4/ansible-redhat-epel/
    version: main
    name: juju4.redhat_epel
